# https://docs.codecov.com/docs/codecovyml-reference
coverage:
  # Range for displaying Red, Yellow, Green transition
  # Used to customize the visible color range in Codecov (Red, Yellow, Green)
  range: 50..70
  round: down
  precision: 1
  status:
    # https://docs.codecov.com/docs/commit-status
    project: &default_settings
      default:
        # Avoid false negatives
        threshold: 1%
        # Set the acceptable minimum passing coverage
        target: 70%
    patch:
      <<: *default_settings

# Test files don't need to be checked for coverage
ignore:
  - "tests"
  - ".github/workflows"

comment:
  layout: "diff, flags, files"
  require_changes: yes
